# Generated by Django 6.0 on 2025-12-22 18:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naziv sastojka', max_length=150)),
                ('code', models.CharField(help_text='Šifra sastojka', max_length=15)),
                ('description', models.TextField(help_text='Opis sastojka', max_length=750)),
                ('base_price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.00'), help_text='Osnovna cijena sastojka', max_digits=18)),
                ('price_modificator', models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.00'), help_text='Modifikator cijene', max_digits=5)),
                ('total_price', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), help_text='Ukupna cijena sastojka', max_digits=18, null=True)),
                ('ingredients', models.ManyToManyField(blank=True, null=True, related_name='products', to='products.ingredient')),
                ('ingredients_from_products', models.ManyToManyField(blank=True, null=True, to='products.product')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
    ]
