# Generated by Django 6.0 on 2025-12-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients_from_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
